# Copyright 2018-2025 Chris Croome
#
# This file is part of the Webarchitects WP-CLI Ansible role.
#
# The Webarchitects WP-CLI Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects WP-CLI Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects WP-CLI Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
variables:
  ANSIBLE_ANY_ERRORS_FATAL: "1"
  ANSIBLE_CALLBACK_RESULT_FORMAT: "yaml"
  ANSIBLE_DEFAULT_VERBOSITY: "1"
  ANSIBLE_DIFF_ALWAYS: "1"
  ANSIBLE_DISPLAY_SKIPPED_HOSTS: "0"
  ANSIBLE_FORCE_COLOR: "1"
  ANSIBLE_INJECT_FACT_VARS: "0"
  ANSIBLE_NOCOWS: "1"
  ANSIBLE_REMOTE_TMP: "/tmp"
  ANSIBLE_ROLES_PATH: "${CI_PROJECT_DIR}/..:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles"
  ANSIBLE_SHELL_ALLOW_WORLD_READABLE_TEMP: "1"
  DEBIAN_FRONTEND: noninteractive
  MOLECULE_VERBOSITY: "0"
  PY_COLORS: "1"
before_script:
  - whoami
  - pwd
  - chmod 700 $(pwd)
  - which ansible
  - ansible --version
  - which yamllint
  - yamllint --version
  - which molecule
  - molecule --version
stages:
  - bookworm
  - forky
  - noble
  - trixie
bookworm:
  image: registry.git.coop/webarch/containers/images/bookworm:20250916
  stage: bookworm
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
forky:
  image: registry.git.coop/webarch/containers/images/forky:20250916
  stage: forky
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
noble:
  image: registry.git.coop/webarch/containers/images/noble:20250916
  stage: noble
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
trixie:
  image: registry.git.coop/webarch/containers/images/trixie:20250916
  stage: trixie
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
...
