---
- name: WP-CLI installed
  get_url:
    url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
    dest: /usr/local/bin/wp
    force: yes
    mode: 0755
  tags:
    - wpcli

- name: WP-CLI Bash completion installed
  get_url:
    url: "https://github.com/wp-cli/wp-cli/raw/master/utils/wp-completion.bash"
    dest: /etc/bash_completion.d/wp-completion.bash
    force: yes
    mode: 0644
  tags:
    - wpcli
