---
- name: Install or upgrade WP-CLI
  block:

    - name: Programmable completion for the Bash shell present
      apt:
        pkg:
          - bash-completion
        state: present

    - name: Directory /etc/bash_completion.d present
      file:
        path: /etc/bash_completion.d
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: Check if WP-CLI is installed
      command: which wp
      check_mode: false
      changed_when: false
      register: wpcli_path
      failed_when: wpcli_path.rc is not regex('0|1')

    - name: Check the installed and latest version of WP-CLI
      block:

        - name: Check what version of WP-CLI is installed
          command: wp --version --allow-root
          register: wpcli_version_check
          check_mode: false
          changed_when: false

        - name: Set a fact for the installed version of WP-CLI
          set_fact:
            wpcli_installed: "{{ wpcli_version_check.stdout | regex_replace('^WP-CLI ') }}"

        - name: Print the installed version of WP-CLI
          debug:
            msg: "WP-CLI version {{ wpcli_installed }} is installed"
            verbosity: 1

        - name: Check the latest version of WP-CLI
          uri:
            url: https://github.com/wp-cli/wp-cli/releases/latest
            method: HEAD
            status_code: 302
            follow_redirects: none
          check_mode: false
          register: wpcli_headers

        - name: Debug WP-CLI URI
          debug:
            msg:
              - "Location: {{ wpcli_headers.location }}"
              - "Path: {{ wpcli_headers.location | urlsplit('path') }}"
              - "Version: {{ wpcli_headers.location | urlsplit('path') | basename | regex_replace('^v') }}"
            verbosity: 2

        - name: Set a fact for the latest version of WP-CLI
          set_fact:
            wpcli_latest: "{{ wpcli_headers.location | urlsplit('path') | basename | regex_replace('^v') }}"

      when: wpcli_path.rc == 0

    - name: Install or upgrade WP-CLI
      block:

        - name: WP-CLI downloaded
          get_url:
            url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            dest: /root/wp
            force: true
            owner: root
            group: root
            mode: 0600
          check_mode: false

        - name: Downloaded version of WP-CLI tested
          command: php /root/wp --info
          check_mode: false
          register: wpcli_info

        - name: WP-CLI in place
          copy:
            src: /root/wp
            dest: /usr/local/bin/wp
            remote_src: true
            owner: root
            group: root
            mode: 0755
          when: ( "WP-CLI version" in wpcli_info.stdout )

        - name: WP-CLI Bash completion installed
          get_url:
            url: https://github.com/wp-cli/wp-cli/raw/master/utils/wp-completion.bash
            dest: /etc/bash_completion.d/wp-completion.bash
            force: true
            owner: root
            group: root
            mode: 0644

      when: ( wpcli_path.rc == 1 ) or ( wpcli_installed is version(wpcli_latest, '<') )

  tags:
    - wpcli
...
