---
- name: Install or upgrade WP-CLI
  block:

    - name: PHP CLI, GPG and programmable completion for the Bash shell present
      ansible.builtin.apt:
        pkg:
          - bash-completion
          - gnupg
          - php-cli
        state: present

    - name: Directory /etc/bash_completion.d present
      ansible.builtin.file:
        path: /etc/bash_completion.d
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Run which to check if WP-CLI is installed
      ansible.builtin.command: which wp
      check_mode: false
      changed_when: false
      register: wpcli_path
      failed_when: wpcli_path.rc is not regex('0|1')

    - name: Check the installed version of WP-CLI
      block:

        - name: Fail if the WP-CLI installed is in a different location from the one to potentially be updated
          assert:
            that:
              - wpcli_path.stdout == wpcli_executable_path

        - name: Check what version of WP-CLI is installed
          ansible.builtin.command: wp --version --allow-root
          register: wpcli_version_check
          check_mode: false
          changed_when: false

        - name: Set a fact for the installed version of WP-CLI
          ansible.builtin.set_fact:
            wpcli_installed: "{{ wpcli_version_check.stdout | regex_replace('^WP-CLI ') }}"

        - name: Print the installed version of WP-CLI
          ansible.builtin.debug:
            msg: "WP-CLI version {{ wpcli_installed }} is installed"
            verbosity: 1

      when: wpcli_path.rc == 0

    - name: Check the latest version of WP-CLI
      ansible.builtin.uri:
        url: https://github.com/wp-cli/wp-cli/releases/latest
        method: HEAD
        status_code: 302
        follow_redirects: none
      check_mode: false
      register: wpcli_headers

    - name: Debug WP-CLI URI
      ansible.builtin.debug:
        msg:
          - "Location: {{ wpcli_headers.location }}"
          - "Version: {{ wpcli_headers.location | urlsplit('path') | basename | regex_replace('^v') }}"
        verbosity: 2

    - name: Set a fact for the latest version of WP-CLI
      ansible.builtin.set_fact:
        wpcli_latest: "{{ wpcli_headers.location | urlsplit('path') | basename | regex_replace('^v') }}"

    - name: Install or upgrade WP-CLI
      block:

        - name: WP-CLI GPG public key present
          ansible.builtin.copy:
            src: A3A2E8F226F0BC06.asc
            dest: "{{ wpcli_download_dir }}/A3A2E8F226F0BC06.asc"
            mode: 0600

        - name: WP-CLI GPG public key imported
          ansible.builtin.command: "gpg --no-tty --import {{ wpcli_download_dir }}/A3A2E8F226F0BC06.asc"
          register: wpcli_gpg_import
          changed_when: ( "not changed" not in wpcli_gpg_import.stderr )

        - name: WP-CLI and GPG signature present
          ansible.builtin.get_url:
            url: "{{ url }}"
            dest: "{{ wpcli_download_dir }}/"
            force: true
            owner: root
            group: root
            mode: 0600
          loop:
            - "https://github.com/wp-cli/wp-cli/releases/download/v{{ wpcli_latest }}/wp-cli-{{ wpcli_latest }}.phar.asc"
            - "https://github.com/wp-cli/wp-cli/releases/download/v{{ wpcli_latest }}/wp-cli-{{ wpcli_latest }}.phar"
          loop_control:
            loop_var: url

        - name: GPG signature verified
          ansible.builtin.command: >
            gpg --no-tty --verify --logger-fd 1
            {{ wpcli_download_dir }}/wp-cli-{{ wpcli_latest }}.phar.asc
            {{ wpcli_download_dir }}/wp-cli-{{ wpcli_latest }}.phar
          check_mode: false
          changed_when: false
          register: wpcli_gpg_verify
          failed_when: ( "Good signature from" not in wpcli_gpg_verify.stdout )

        - name: WP-CLI in place
          ansible.builtin.copy:
            src: "{{ wpcli_download_dir }}/wp-cli-{{ wpcli_latest }}.phar"
            dest: "{{ wpcli_executable_path }}"
            remote_src: true
            owner: root
            group: root
            mode: 0755
            validate: php %s --info

        - name: WP-CLI Bash completion installed
          ansible.builtin.get_url:
            url: https://github.com/wp-cli/wp-cli/raw/master/utils/wp-completion.bash
            dest: /etc/bash_completion.d/wp-completion.bash
            force: true
            owner: root
            group: root
            mode: 0644

      when: ( wpcli_path.rc == 1 ) or ( wpcli_installed is version(wpcli_latest, '<') )

  tags:
    - wpcli
...
