# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects WP-CLI Ansible role.
#
# The Webarchitects WP-CLI Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects WP-CLI Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects WP-CLI Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Lint
  become: false
  connection: local
  gather_facts: false
  hosts:
    - localhost
  tasks:

    - name: Check Jinja2 syntax
      ansible.builtin.command: find -type f -name '*.j2' -exec ansiblej2lint.py {} +
      check_mode: false
      args:
        chdir: ../..
      changed_when: false

    - name: YAML lint
      ansible.builtin.command: yamllint -f colored -c .yamllint .
      check_mode: false
      args:
        chdir: ../..
      changed_when: false

    - name: Ansible lint
      ansible.builtin.command: ansible-lint -c .ansible-lint --force-color .
      check_mode: false
      args:
        chdir: ../..
      changed_when: false
# vim: syntax=yaml
...
