# Copyright 2018-2024 Chris Croome
#
# This file is part of the Webarchitects WP-CLI Ansible role.
#
# The Webarchitects WP-CLI Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects WP-CLI Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects WP-CLI Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
dependency:
  name: galaxy
platforms:
  - name: instance
provisioner:
  name: ansible
  config_options:
    defaults:
      ansible_managed: Ansible managed
    # host_vars:
    #   instance:
    #     ansible_user: ansible
  options:
    D: true
verifier:
  name: ansible
    # host_vars:
    #   instance:
    #     ansible_user: ansible
...
